---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goof
  name: goof
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
      - image: ${DOCKER_ACCOUNT}/java-goof:latest
        imagePullPolicy: Always
        name: java-goof
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
              - cat
              - /healthcheck
      securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities: 
            drop: ["ALL"]
            add: ['NET_BIND_SERVICE']

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goof
  name: goof
spec:
  type: LoadBalancer
  loadBalancerSourceRanges: [100.10.0.0/16]
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: goof
